package thelm.jargca;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
		modid = JARGCA.MOD_ID,
		name = JARGCA.NAME,
		version = JARGCA.VERSION,
		dependencies = JARGCA.DEPENDENCIES
		)
public class JARGCA {
	public static final String MOD_ID = "jargca";
	public static final String NAME = "JARGCA";
	public static final String VERSION = "1.12.2-1.0.0.0";
	public static final String DEPENDENCIES = "required-before:jaopca@[1.12.2-2.3.2,);";
	@Instance(JARGCA.MOD_ID)
	public static JARGCA core;
	public static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.version = VERSION;
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A addon to JAOPCA that aims to make mods with resource generation support more materials.";
	}
}
